# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Product.create(name: "CB Shine", picture: "cbshine.jpg", category: "Motorcycle", cylinder: 125, engine: "Air", color1: "black", color2: "gray", color3: "brown", color4: "red", image1: "shine-1.png", image2: "shine-2.jpg", image3: "shine-3.jpg", image4: "shine-4.jpg", thumb1: "shine-thumb-1", thumb2: "shine-thumb-2", thumb3: "shine-thumb-3", thumb4: "shine-thumb-4")
Product.create(name: "CBF Stunner", picture: "cbfstunner.jpg", category: "Motorcycle", cylinder: 125, engine: "Air", color1: "red", color2: "yellow", color3: "green", color4: "black", image1: "stunner-1.png", image2: "stunner-2.jpg", image3: "stunner-3.jpg", image4: "stunner-4.jpg", thumb1: "stunner-thumb-1", thumb2: "stunner-thumb-2", thumb3: "stunner-thumb-3", thumb4: "stunner-thumb-4")
Product.create(name: "CB Trigger", picture: "cbtrigger.jpg", category: "Motorcycle", cylinder: 150, engine: "Air", color1: "black", color2: "green", color3: "white", color4: "red", image1: "trigger-1.png", image2: "trigger-2.jpg", image3: "trigger-3.jpg", image4: "trigger-4.jpg", thumb1: "trigger-thumb-1", thumb2: "trigger-thumb-2", thumb3: "trigger-thumb-3", thumb4: "trigger-thumb-4")
Product.create(name: "CB Twister", picture: "cbtwister.jpg", category: "Motorcycle", cylinder: 110, engine: "Air", color1: "gray", color2: "black", color3: "yellow", color4: "red", image1: "twister-1.png", image2: "twister-2.jpg", image3: "twister-3.jpg", image4: "twister-4.jpg", thumb1: "twister-thumb-1", thumb2: "twister-thumb-2", thumb3: "twister-thumb-3", thumb4: "twister-thumb-4")
Product.create(name: "CBR 150R", picture: "cbr150r.jpg", category: "Motorcycle", cylinder: 150, engine: "Liquid", color1: "orange", color2: "green", color3: "white", color4: "red", image1: "cbr150-1.png", image2: "cbr150-2.jpg", image3: "cbr150-3.jpg", image4: "cbr150-4.jpg", thumb1: "cbr150-thumb-1", thumb2: "cbr150-thumb-2", thumb3: "cbr150-thumb-3", thumb4: "cbr150-thumb-4")
Product.create(name: "CBR 250R", picture: "cbr250r.jpg", category: "Motorcycle", cylinder: 250, engine: "Liquid", color1: "gray", color2: "white", color3: "red", image1: "cbr250-1.png", image2: "cbr250-2.jpg", image3: "cbr250-3.jpg", thumb1: "cbr250-thumb-1", thumb2: "cbr250-thumb-2", thumb3: "cbr250-thumb-3")
Product.create(name: "CB Unicorn 160", picture: "cbunicorn160.jpg", category: "Motorcycle", cylinder: 160, engine: "Air", color1: "red", color2: "gray", color3: "black", color4: "white", image1: "unicorn-1.png", image2: "unicorn-2.jpg", image3: "unicorn-3.jpg", image4: "unicorn-4.jpg", thumb1: "unicorn-thumb-1", thumb2: "unicorn-thumb-2", thumb3: "unicorn-thumb-3", thumb4: "unicorn-thumb-4")

Product.create(name: "CD 110", picture: "cd110.jpg", category: "Dream Series", cylinder: 110, engine: "Air", color1: "red", color2: "gray", color3: "blue", image1: "cd110-1.png", image2: "cd110-2.jpg", image3: "cd110-3.jpg", thumb1: "cd110-thumb-1", thumb2: "cd110-thumb-2", thumb3: "cd110-thumb-3")
Product.create(name: "Dream Yuga", picture: "dreamyuga.jpg", category: "Dream Series", cylinder: 110, engine: "Air", color1: "black", color2: "blue", color3: "gray", color4: "red", image1: "dreamyuga-1.png", image2: "dreamyuga-2.jpg", image3: "dreamyuga-3.jpg", image4: "dreamyuga-4.jpg", thumb1: "dreamyuga-thumb-1", thumb2: "dreamyuga-thumb-2", thumb3: "dreamyuga-thumb-3", thumb4: "dreamyuga-thumb-4")
Product.create(name: "Dream Neo", picture: "dreamneo.jpg", category: "Dream Series", cylinder: 110, engine: "Air", color1: "black", color2: "red", color3: "silver", color4: "gray", image1: "dreamneo-1.png", image2: "dreamneo-2.jpg", image3: "dreamneo-3.jpg", image4: "dreamneo-4.jpg", thumb1: "dreamneo-thumb-1", thumb2: "dreamneo-thumb-2", thumb3: "dreamneo-thumb-3", thumb4: "dreamneo-thumb-4")

Product.create(name: "Activa 3G", picture: "activa3g.jpg", category: "Scooter", cylinder: 110, engine: "Air", color1: "black", color2: "white", color3: "red", color4: "blue", image1: "activa3g-1.png", image2: "activa3g-2.jpg", image3: "activa3g-3.jpg", image4: "activa3g-4.jpg", thumb1: "activa3g-thumb-1", thumb2: "activa3g-thumb-2", thumb3: "activa3g-thumb-3", thumb4: "activa3g-thumb-4")
Product.create(name: "Activa i", picture: "activai.jpg", category: "Scooter", cylinder: 110, engine: "Air", color1: "purple", color2: "red", color3: "white", color4: "brown", image1: "activai-1.png", image2: "activai-2.jpg", image3: "activai-3.jpg", image4: "activai-4.jpg", thumb1: "activai-thumb-1", thumb2: "activai-thumb-2", thumb3: "activai-thumb-3", thumb4: "activai-thumb-4")
Product.create(name: "Activa 125", picture: "activa125.jpg", category: "Scooter", cylinder: 125, engine: "Air", color1: "silver", color2: "blue", color3: "white", color4: "black", image1: "activa125-1.png", image2: "activa125-2.jpg", image3: "activa125-3.jpg", image4: "activa125-4.jpg", thumb1: "activa125-thumb-1", thumb2: "activa125-thumb-2", thumb3: "activa125-thumb-3", thumb4: "activa125-thumb-4")
Product.create(name: "Dio", picture: "dio.jpg", category: "Scooter", cylinder: 110, engine: "Air", color1: "red", color2: "black", color3: "green", color4: "blue", image1: "dio-1.png", image2: "dio-2.jpg", image3: "dio-3.jpg", image4: "dio-4.jpg", thumb1: "dio-thumb-1", thumb2: "dio-thumb-2", thumb3: "dio-thumb-3", thumb4: "dio-thumb-4")
Product.create(name: "Aviator", picture: "aviator.jpg", category: "Scooter", cylinder: 110, engine: "Air", color1: "black", color2: "gold", color3: "red", color4: "white", image1: "aviator-1.png", image2: "aviator-2.jpg", image3: "aviator-3.jpg", image4: "aviator-4.jpg", thumb1: "aviator-thumb-1", thumb2: "aviator-thumb-2", thumb3: "aviator-thumb-3", thumb4: "aviator-thumb-4")

Product.create(name: "Gold Wing", picture: "goldwing.jpg", category: "Super Bikes", cylinder: 1832, engine: "Liquid", color1: "red", color2: "white", image1: "goldwing-1.png", image2: "goldwing-2.jpg", thumb1: "goldwing-thumb-1", thumb2: "goldwing-thumb-2")
Product.create(name: "VT 1300CX", picture: "vt1300cx.jpg", category: "Super Bikes", cylinder: 1312, engine: "Liquid", color1: "black", image1: "vt1300cx-1.png", thumb1: "vt1300cx-thumb-1")
Product.create(name: "VFR 1200F", picture: "vfr1200f.jpg", category: "Super Bikes", cylinder: 1237, engine: "Liquid", color1: "red", image1: "vfr1200f-1.png", thumb1: "vfr1200f-thumb-1")
Product.create(name: "CBR1000RR", picture: "cbr1000rr.jpg", category: "Super Bikes", cylinder: 1000, engine: "Liquid", color1: "red", image1: "cbr1000rr-1.png", image2: "cbr1000rr-2.jpg", image4: "cbr1000rr-4.jpg")
Product.create(name: "CB1000R", picture: "cb1000r.jpg", category: "Super Bikes", cylinder: 1000, engine: "Liquid", color1: "white", color2: "red", color3: "black", image1: "cb1000r-1.png", image2: "cb1000r-2.jpg", image3: "cb1000r-3.jpg", thumb1: "cb1000r-thumb-1", thumb2: "cb1000r-thumb-2", thumb3: "cb1000r-thumb-3")
